### ISSUE TITLE
output of loading info

### ISSUE THREAD

**Issue by zoggy** [sanette/tsdl-ttf#6]
Hi,

"INFO: Loading Sdl_ttf, Target = ..." is now printed when module is loaded, i.e. before application code can set sdl log priority level:
https://github.com/sanette/tsdl-ttf/blob/4ca2f4ba7567ca474556b0c23a4e4bfcac923fbe/src/tsdl_ttf.ml#L68
Could it be moved somewhere else or use another category, for example the system category whose default log priority is critical ?

**Comment by sanette** [comment]
That sounds a good idea. Feel free to submit a PR.
